title = "Sacre Pagina"
baseURL = 'https://thatpigeonguy.github.io/sacre-pagina/'
languageCode = 'en-us'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = false
  taglist = false
  showrss = false